# all our libraries and projects for frontent-/commandline-implementations
[workspace]
members=[
    "runtime_unix",
    "mathlib_renderer",
    "parselib_yaml",
    "wasm_webpack"
]
resolver = "1"

[profile.release]
lto = true
opt-level = 3